language: node_js
node_js:
  - stable
  - lts/*
  - 10.13.0
env:
  - WEBPACK_CORE=5
jobs:
  exclude:
  - node_js: 10.13.0
    env: WEBPACK_CORE=next
before_install:
  - stty columns 120
install:
  - travis_retry npm install --ignore-scripts
  - travis_retry npm install "webpack@$WEBPACK_CORE" --ignore-scripts
script:
  - travis_retry npm test
